### ISSUE TITLE
Better documentation check

### ISSUE THREAD

**Issue by carloskiki** [jonhoo/rust-ci-conf#22]
Instead of running `cargo doc` in the check.yml workflow for checking that the documentation builds successfully, we could alternatively (or also) check using [`dtolnay/cargo-docs-rs`](https://github.com/dtolnay/cargo-docs-rs) so that the check is closer to what the `docs.rs` environment does.

From the project README:
> Run `cargo rustdoc` with the same options that would be used by docs.rs, taking into account the `package.metadata.docs.rs` configured in Cargo.toml.

If you think its a good idea to add this check/replace the old one, let me know and I will open a PR!

**Comment by joshka** [comment]
Yes please.

**Comment by jonhoo** [comment]
Oh, yeah, that's a great idea! Please do :)
