### ISSUE TITLE
License

### ISSUE THREAD

**Issue by BennoLossin** [jonhoo/rust-ci-conf#6]
What is the license of this repo? Just wanted to make sure I could use this in a project with `Apache 2.0 OR MIT`.

**Comment by jonhoo** [comment]
Ah! The license here is indeed Apache 2.0 OR MIT. However, I can't put the license files in the repo itself, because that might break the workflow where people merge from this repo into their own.

**Comment by BennoLossin** [comment]
Yeah figured that would be the reason for why there is no license, thanks for the info!
