### ISSUE TITLE
safety/sanitizers does not work with only workspace

### ISSUE THREAD

**Issue by alexkazik** [jonhoo/rust-ci-conf#8]
If the Cargo.toml contains only a workspace then the sed part does not help.

I don't know enough about sed to create a patch ,but if it's changed to
"insert before first features or workspace"
then it should work just fine.

**Comment by jonhoo** [comment]
Hmm, when you say "does not help"/"does not work", what doesn't work? What error do you see?

**Comment by alexkazik** [comment]
I don't see any error, but the modified Cargo.toml doesn't contain the `[profile.dev]` section (as it's cat'ed) and since the section is missing the next step with `opt-level = 1` is also not added. (And I thought that the opt-level thing is required.)

Try it on a Cargo.toml with only a workspace and nothing else.

**Comment by jonhoo** [comment]
Ohh, I see what you mean!

Could you give the fix in https://github.com/jonhoo/rust-ci-conf/pull/9 a try?

**Comment by alexkazik** [comment]
Works like a charm with my setup.

But breaks when the Cargo.toml has no trailing newline.

**Comment by jonhoo** [comment]
It works fine for me even with no trailing newline :thinking: Can you give an example TOML where it breaks?

**Comment by alexkazik** [comment]
Sure.

[Cargo.toml.gz](https://github.com/jonhoo/rust-ci-conf/files/11312590/Cargo.toml.gz)

Edit:
it will result in
```
[workspace]
members = [
  "demo",
][profile.dev]
```

**Comment by jonhoo** [comment]
Nice, thanks. Updated the PR. How's that for you?

**Comment by alexkazik** [comment]
That does the trick.

(Though my code has a trailing newline, I've checked that only to be sure it'll work.)
